"""
UC15 GST Compliance Agent — Validation Results & Reports Contracts
"""
from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from decimal import Decimal
from typing import Any, Dict, List, Optional

from app.domain.enums.compliance_status import ComplianceStatus
from app.domain.enums.rule_category import RuleCategory
from app.domain.enums.severity import Severity
from app.domain.enums.validation_status import ValidationStatus


@dataclass
class ValidationResult:
    """
    Standard result contract returned by all compliance rules.
    Extensible for future risk, ML, and financial exposure engines.
    Fully compatible with legacy GateResult via name, detail, and gate_no.
    """
    rule_id: str
    rule_name: str
    status: str          # PASS | FAIL | WARNING | NOT_APPLICABLE | ERROR
    message: str
    severity: str = "MEDIUM"
    category: str = "OTHER"
    actual_value: Optional[Any] = None
    expected_value: Optional[Any] = None
    evidence: Optional[Any] = None
    metadata: Dict[str, Any] = field(default_factory=dict)

    # Legacy & Sprint 1 Gate Compatibility
    gate_no: Optional[int] = None
    name: str = ""
    detail: str = ""

    # Two-Tier Gate Engine Contract (v3.0)
    applicability: str = "APPLICABLE"  # APPLICABLE | NOT_APPLICABLE | REVIEW | UNKNOWN
    applicability_reason: Optional[str] = None

    # Rule version and lineage
    rule_version: str = "2.0"
    reference_id: Optional[str] = None
    reference_version: Optional[str] = None

    # S21 Explainability & Traceability
    observed_value: Optional[Any] = None
    calculation_trace: Optional[Dict[str, Any]] = None
    financial_exposure_type: Optional[str] = None

    # Multi-Vector Confidence Model (Phase 5)
    financial_impact: Optional[Decimal] = None
    confidence: Optional[float] = 1.0
    rule_confidence: float = 1.0
    evidence_confidence: float = 1.0
    data_quality_confidence: float = 1.0
    overall_decision_confidence: float = 1.0

    source: Optional[str] = None
    timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())

    def __post_init__(self):
        if not self.name:
            self.name = self.rule_name
        if not self.detail:
            self.detail = self.message
        if self.observed_value is None and self.actual_value is not None:
            self.observed_value = self.actual_value
        elif self.actual_value is None and self.observed_value is not None:
            self.actual_value = self.observed_value
        if isinstance(self.status, ValidationStatus):
            self.status = self.status.value
        if isinstance(self.severity, Severity):
            self.severity = self.severity.value
        if isinstance(self.category, RuleCategory):
            self.category = self.category.value

    def to_dict(self) -> Dict[str, Any]:
        """Serialize into dictionary."""
        from dataclasses import asdict
        return asdict(self)


# Compatibility alias for existing GateResult imports
GateResult = ValidationResult


@dataclass
class ValidationReport:
    """
    Structured execution report generated by the ValidationEngine for an invoice.
    """
    invoice_id: str
    results: List[ValidationResult] = field(default_factory=list)
    passed_count: int = 0
    failed_count: int = 0
    warning_count: int = 0
    not_applicable_count: int = 0
    needs_review_count: int = 0
    execution_timestamp: str = field(default_factory=lambda: datetime.now(timezone.utc).isoformat())
    metadata: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self):
        if self.results and (self.passed_count == 0 and self.failed_count == 0 and self.not_applicable_count == 0 and self.needs_review_count == 0):
            self.passed_count = sum(1 for r in self.results if r.status == "PASS")
            self.failed_count = sum(1 for r in self.results if r.status == "FAIL")
            self.warning_count = sum(1 for r in self.results if r.status == "WARNING")
            self.not_applicable_count = sum(1 for r in self.results if r.status == "NOT_APPLICABLE")
            self.needs_review_count = sum(1 for r in self.results if r.status == "NEEDS_REVIEW")

    @property
    def summary(self) -> Dict[str, int]:
        return {
            "passed": self.passed_count,
            "failed": self.failed_count,
            "warnings": self.warning_count,
            "not_applicable": self.not_applicable_count,
            "needs_review": self.needs_review_count,
        }

    def to_dict(self) -> Dict[str, Any]:
        return {
            "invoice_id": self.invoice_id,
            "results": [r.to_dict() for r in self.results],
            "summary": self.summary,
            "execution_timestamp": self.execution_timestamp,
            "metadata": self.metadata,
        }


@dataclass
class ComplianceDecision:
    """
    Overall compliance verdict for an invoice produced by the DecisionEngine.
    Preserves exact attributes for existing UI, reporting, and CLI output.
    """
    invoice_no: str
    invoice_date: str
    direction: str
    counterparty_gstin: str
    counterparty_name: str
    place_of_supply: str
    hsn_code: str
    item_desc: str
    taxable_value_inr: float
    total_amt: float
    gates: List[ValidationResult]
    failed_gate_count: int
    status: str
    justification: str
    recommended_action: str
    sap_action: str
    audit_trail_ref: str
    hard_override: bool
    alerts: List[str] = field(default_factory=list)

    # Sprint 2 Data Quality extensions
    data_quality_results: List[ValidationResult] = field(default_factory=list)

    # Sprint 3 Risk Engine extensions
    severity: Optional[str] = None
    risk_score: Optional[float] = None
    risk_level: Optional[str] = None
    priority: Optional[str] = None
    risk_assessment: Optional[Any] = None
    financial_impact: Optional[Decimal] = None
    recommendations: List[str] = field(default_factory=list)

    # Sprint 4 Reference Intelligence extensions
    reference_snapshot: Optional[Any] = None

    @property
    def invoice_id(self) -> str:
        return self.invoice_no

    def to_dict(self) -> Dict[str, Any]:
        from dataclasses import asdict
        return asdict(self)

